### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by sgehrman** [liquidapps-io/zeus-coldtoken-sample#3]
$ zeus unbox coldtoken
⚙️Unboxing: coldtoken
ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.require.extensions.<computed> [as .js] (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)

**Comment by sgehrman** [comment]
Fixed it, needed nodejs 10 (didn't try 11)
